apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{.Release.Name}}"
  namespace: "{{.Values.deploy.namespace}}"
type: Opaque
stringData:
    DB_PASSWORD_EXTRACTION: "{{.Values.deploy.db_password_extraction}}"
    DB_PASSWORD_INSERTIONS: "{{.Values.deploy.db_password_insertions}}"